In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
X_feature = iris_dataset.data
Y_target = iris_dataset.target

In [5]:
X_new = [[3,5,4,1],[5,3,4,2]]

In [6]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [7]:
logreg.fit(X_feature,Y_target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
logreg.predict(X_new)

array([0, 2])

In [9]:
import pickle as pkl

In [10]:
persist_model = pkl.dumps(logreg)
persist_model

'ccopy_reg\n_reconstructor\np0\n(csklearn.linear_model.logistic\nLogisticRegression\np1\nc__builtin__\nobject\np2\nNtp3\nRp4\n(dp5\nS\'warm_start\'\np6\nI00\nsS\'C\'\np7\nF1.0\nsS\'max_iter\'\np8\nI100\nsS\'verbose\'\np9\nI0\nsS\'intercept_scaling\'\np10\nI1\nsS\'dual\'\np11\nI00\nsS\'fit_intercept\'\np12\nI01\nsS\'classes_\'\np13\ncnumpy.core.multiarray\n_reconstruct\np14\n(cnumpy\nndarray\np15\n(I0\ntp16\nS\'b\'\np17\ntp18\nRp19\n(I1\n(L3L\ntp20\ncnumpy\ndtype\np21\n(S\'i4\'\np22\nI0\nI1\ntp23\nRp24\n(I3\nS\'<\'\np25\nNNNI-1\nI-1\nI0\ntp26\nbI00\nS\'\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x02\\x00\\x00\\x00\'\np27\ntp28\nbsS\'solver\'\np29\nS\'liblinear\'\np30\nsS\'n_iter_\'\np31\ng14\n(g15\n(I0\ntp32\ng17\ntp33\nRp34\n(I1\n(L1L\ntp35\ng21\n(S\'i4\'\np36\nI0\nI1\ntp37\nRp38\n(I3\nS\'<\'\np39\nNNNI-1\nI-1\nI0\ntp40\nbI00\nS\'\\x07\\x00\\x00\\x00\'\np41\ntp42\nbsS\'penalty\'\np43\nS\'l2\'\np44\nsS\'multi_class\'\np45\nS\'ovr\'\np46\nsS\'random_state\'\np47\nNsS\'tol\'\np48\nF0.0001\n

In [11]:
from sklearn.externals import joblib
joblib.dump(logreg,'regresfilename.pkl')

['regresfilename.pkl',
 'regresfilename.pkl_01.npy',
 'regresfilename.pkl_02.npy',
 'regresfilename.pkl_03.npy',
 'regresfilename.pkl_04.npy']

In [12]:
new_logreg_estimator = joblib.load('regresfilename.pkl')

In [13]:
new_logreg_estimator

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [14]:
new_logreg_estimator.predict(X_new)

array([0, 2])